- name: start php7.2-fpm
  service:
    name: php7.2-fpm
    enabled: yes
    state: started

- name: restart php7.2-fpm
  service:
    name: php7.2-fpm
    enabled: yes
    state: restarted

- name: reload php7.2-fpm
  service:
    name: php7.2-fpm
    enabled: yes
    state: reloaded

- include: ../nginx/handlers/main.yml